require 'jekyll/scholar'
require 'jekyll/scholar/extras/extras_utilities'
require 'jekyll/scholar/extras/bibliography_year'
require 'jekyll/scholar/extras/bibliography_bytype'
require 'jekyll/scholar/extras/bibliography_byapplication'
require 'jekyll/scholar/extras/bibliography_byimaging'
